export default defineEventHandler(async (event) => {
  let { locale } = getQuery(event) as { locale?: string };

  if (!locale) {
    locale = "sv"; // if missing add default locale
  }

  console.log(`Fetching locations with locale param: ${locale}`);
  const originalLocations = [
    {
      id: "40",
      name_sv: "Biomedicinska biblioteket",
      name_en: "Biomedical Library",
      pickup_location_id: "40",
      categories: ["PICKUP"],
      sublocations: [
        {
          id: "400005",
          location_id: "40",
          name_sv: "Plan 3 (före 1980 måste beställas)",
          name_en: "Plan 3 (före 1980 måste beställas)",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "1",
          is_kursbok_loc: "",
        },
        {
          id: "400051",
          location_id: "40",
          name_sv: "Informationsdisken",
          name_en: "Informationsdisken",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "1",
          is_kursbok_loc: "",
        },
        {
          id: "400041",
          location_id: "40",
          name_sv: "Botaniska trädgården",
          name_en: "Botaniska trädgården",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "400050",
          location_id: "40",
          name_sv: "Informationsdisken",
          name_en: "Informationsdisken",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "1",
          is_kursbok_loc: "",
        },
        {
          id: "400010",
          location_id: "40",
          name_sv: "Plan 3, Avhandlingar",
          name_en: "Plan 3, Avhandlingar",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "1",
          is_kursbok_loc: "",
        },
        {
          id: "400004",
          location_id: "40",
          name_sv: "Plan 5",
          name_en: "Plan 5",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "1",
        },
        {
          id: "400009",
          location_id: "40",
          name_sv: "Plan 5",
          name_en: "Plan 5",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "400030",
          location_id: "40",
          name_sv: "Plan 4",
          name_en: "Plan 4",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "400002",
          location_id: "40",
          name_sv: "Biomed bibl MAG2",
          name_en: "Biomed bibl MAG2",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "400006",
          location_id: "40",
          name_sv: "Plan 5",
          name_en: "Plan 5",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "400001",
          location_id: "40",
          name_sv: "Biomed bibl MON MAG",
          name_en: "Biomed bibl MON MAG",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "400032",
          location_id: "40",
          name_sv: "Plan 3, Boksamling",
          name_en: "Plan 3, Boksamling",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "1",
          is_kursbok_loc: "",
        },
        {
          id: "400003",
          location_id: "40",
          name_sv: "Plan 3 (före 1980 måste beställas)",
          name_en: "Plan 3 (före 1980 måste beställas)",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "1",
          is_kursbok_loc: "",
        },
        {
          id: "400040",
          location_id: "40",
          name_sv: "Plan 3 (före 1980 måste beställas)",
          name_en: "Plan 3 (före 1980 måste beställas)",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "1",
          is_kursbok_loc: "",
        },
        {
          id: "400013",
          location_id: "40",
          name_sv: "Plan 3 (före 1980 måste beställas)",
          name_en: "Plan 3 (före 1980 måste beställas)",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "1",
          is_kursbok_loc: "",
        },
        {
          id: "400012",
          location_id: "40",
          name_sv: "Plan 3 (före 1980 måste beställas)",
          name_en: "Plan 3 (före 1980 måste beställas)",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "1",
          is_kursbok_loc: "",
        },
        {
          id: "400011",
          location_id: "40",
          name_sv: "Plan 3 (före 1980 måste beställas)",
          name_en: "Plan 3 (före 1980 måste beställas)",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "1",
          is_kursbok_loc: "",
        },
        {
          id: "400014",
          location_id: "40",
          name_sv: "Informationsdisken",
          name_en: "Informationsdisken",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "400033",
          location_id: "40",
          name_sv: "Plan 3, Boksamling",
          name_en: "Plan 3, Boksamling",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "1",
          is_kursbok_loc: "",
        },
        {
          id: "400008",
          location_id: "40",
          name_sv: "Plan 5",
          name_en: "Plan 5",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "400060",
          location_id: "40",
          name_sv: "Studietorget Hälsovetarbacken (Används ej)",
          name_en: "Studietorget Hälsovetarbacken (Används ej)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "400020",
          location_id: "40",
          name_sv: "Biomed bibl VALVET",
          name_en: "Biomed bibl VALVET",
          is_open_loc: "",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "400100",
          location_id: "40",
          name_sv: "Biomed Hänvisningspost",
          name_en: "Biomed Hänvisningspost",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "400300",
          location_id: "40",
          name_sv: "Biomed Inköp",
          name_en: "Biomed Inköp",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "400000",
          location_id: "40",
          name_sv: "Plan 3 (före 1980 måste beställas)",
          name_en: "Plan 3 (före 1980 måste beställas)",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "1",
          is_kursbok_loc: "",
        },
        {
          id: "400088",
          location_id: "40",
          name_sv: "Gm Bestånd bib lvl f",
          name_en: "Gm Bestånd bib lvl f",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "400089",
          location_id: "40",
          name_sv: "Gm Bestånd bib lvl g",
          name_en: "Gm Bestånd bib lvl g",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "400099",
          location_id: "40",
          name_sv: "Fjärrlån",
          name_en: "Fjärrlån",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
      ],
    },
    {
      id: "42",
      name_sv: "Samhällsvetenskapliga biblioteket",
      name_en: "Social Sciences Library",
      pickup_location_id: "42",
      categories: ["PICKUP"],
      sublocations: [
        {
          id: "420089",
          location_id: "42",
          name_sv: "Gk Bestånd bib lvl g",
          name_en: "Gk Bestånd bib lvl g",
          is_open_loc: "",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420099",
          location_id: "42",
          name_sv: "Fjärrlån",
          name_en: "Fjärrlån",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420030",
          location_id: "42",
          name_sv: "Föreningsgatan, boksamling",
          name_en: "Föreningsgatan, boksamling",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420100",
          location_id: "42",
          name_sv: "Sambibl  Hänvisningspost",
          name_en: "Sambibl  Hänvisningspost",
          is_open_loc: "",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420006",
          location_id: "42",
          name_sv: "Sambibl 06 (används ej)",
          name_en: "Sambibl 06 (används ej)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420011",
          location_id: "42",
          name_sv: "Sambibl 11 (används ej)",
          name_en: "Sambibl 11 (används ej)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420003",
          location_id: "42",
          name_sv: "Föreningsgatan entré",
          name_en: "Föreningsgatan entré",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420007",
          location_id: "42",
          name_sv: "Föreningsgatan, informationsdisk",
          name_en: "Föreningsgatan, informationsdisk",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420300",
          location_id: "42",
          name_sv: "Sambibl Inköp",
          name_en: "Sambibl Inköp",
          is_open_loc: "",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420001",
          location_id: "42",
          name_sv: "Föreningsgatan, kursbokssamling",
          name_en: "Föreningsgatan, kursbokssamling",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "1",
        },
        {
          id: "420002",
          location_id: "42",
          name_sv: "Föreningsgatan, läsesalen",
          name_en: "Föreningsgatan, läsesalen",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "1",
        },
        {
          id: "420031",
          location_id: "42",
          name_sv: "Föreningsgatan, tidskrifter",
          name_en: "Föreningsgatan, tidskrifter",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420004",
          location_id: "42",
          name_sv: "Föreningsgatan, boksamling referensböcker",
          name_en: "Föreningsgatan, boksamling referensböcker",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420404",
          location_id: "42",
          name_sv: "Föreningsgatan, läsesalen",
          name_en: "Föreningsgatan, läsesalen",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420020",
          location_id: "42",
          name_sv: "Vasagatan plan 4",
          name_en: "Vasagatan plan 4",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420000",
          location_id: "42",
          name_sv: "Vasagatan entréplan",
          name_en: "Vasagatan entréplan",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420029",
          location_id: "42",
          name_sv: "Sambibl MAG PLAN 4",
          name_en: "Sambibl MAG PLAN 4",
          is_open_loc: "",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420010",
          location_id: "42",
          name_sv: "Vasagatan entréplan, läsesalen, referensböcker",
          name_en: "Vasagatan entréplan, läsesalen, referensböcker",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "420005",
          location_id: "42",
          name_sv: "Vasagatan plan 4, referensböcker",
          name_en: "Vasagatan plan 4, referensböcker",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
      ],
    },
    {
      id: "43",
      name_sv: "Depå Änggården",
      name_en: "Depot Änggården",
      pickup_location_id: "44",
      categories: [],
      sublocations: [
        {
          id: "430100",
          location_id: "43",
          name_sv: "Änggården depå Hänvisningspost",
          name_en: "Änggården depå Hänvisningspost",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "430011",
          location_id: "43",
          name_sv: "Änggården depå RUM 106",
          name_en: "Änggården depå RUM 106",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "430012",
          location_id: "43",
          name_sv: "Änggården depå RUM 110",
          name_en: "Änggården depå RUM 110",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "430021",
          location_id: "43",
          name_sv: "Änggården depå RUM 206",
          name_en: "Änggården depå RUM 206",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
      ],
    },
    {
      id: "44",
      name_sv: "Humanistiska biblioteket",
      name_en: "Humanities Library",
      pickup_location_id: "44",
      categories: ["PICKUP"],
      sublocations: [
        {
          id: "440099",
          location_id: "44",
          name_sv: "Fjärrlån",
          name_en: "Fjärrlån",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440000",
          location_id: "44",
          name_sv: "Humanistiska biblioteket",
          name_en: "Humanistiska biblioteket",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440055",
          location_id: "44",
          name_sv: "Plan 5 Öst",
          name_en: "Plan 5 Öst",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440053",
          location_id: "44",
          name_sv: "Plan 5 Väst",
          name_en: "Plan 5 Väst",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440066",
          location_id: "44",
          name_sv: "Plan 6A Öst",
          name_en: "Plan 6A Öst",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440060",
          location_id: "44",
          name_sv: "Plan 6A Väst",
          name_en: "Plan 6A Väst",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440063",
          location_id: "44",
          name_sv: "Plan 6B",
          name_en: "Plan 6B",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440069",
          location_id: "44",
          name_sv: "Humbibl BLOMSTEDT",
          name_en: "Humbibl BLOMSTEDT",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440059",
          location_id: "44",
          name_sv: "Humbibl DISK SAML",
          name_en: "Humbibl DISK SAML",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440077",
          location_id: "44",
          name_sv: "Entréplan, Informationsdisken",
          name_en: "Entréplan, Informationsdisken",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440100",
          location_id: "44",
          name_sv: "Humbibl Hänvisningspost",
          name_en: "Humbibl Hänvisningspost",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440011",
          location_id: "44",
          name_sv: "Hvitfeldtska samlingen",
          name_en: "Hvitfeldtska samlingen",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440068",
          location_id: "44",
          name_sv: "Plan 6B, Iberoamerikanska samlingen",
          name_en: "Plan 6B, Iberoamerikanska samlingen",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "446200",
          location_id: "44",
          name_sv: "Plan 6A Musik och dramatik Inforummet",
          name_en: "Plan 6A Musik och dramatik Inforummet",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440300",
          location_id: "44",
          name_sv: "Humbibl Inköp",
          name_en: "Humbibl Inköp",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440076",
          location_id: "44",
          name_sv: "Entréplan, Bibliografier",
          name_en: "Entréplan, Bibliografier",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440001",
          location_id: "44",
          name_sv: "Entréplan, Läsesalen",
          name_en: "Entréplan, Läsesalen",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440084",
          location_id: "44",
          name_sv: "Humbibl LJUD",
          name_en: "Humbibl LJUD",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440200",
          location_id: "44",
          name_sv: "Humbibl LJUD VIDEO (teaterpjäser)",
          name_en: "Humbibl LJUD VIDEO (teaterpjäser)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440085",
          location_id: "44",
          name_sv: "Humbibl LJUD VIDEOBIL",
          name_en: "Humbibl LJUD VIDEOBIL",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440086",
          location_id: "44",
          name_sv: "Humbibl MAG (komb)",
          name_en: "Humbibl MAG (komb)",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440003",
          location_id: "44",
          name_sv: "Humbibl MAG PER",
          name_en: "Humbibl MAG PER",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440010",
          location_id: "44",
          name_sv: "Humbibl MAG10",
          name_en: "Humbibl MAG10",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440020",
          location_id: "44",
          name_sv: "Humbibl MAG20",
          name_en: "Humbibl MAG20",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440021",
          location_id: "44",
          name_sv: "Humbibl MAG21",
          name_en: "Humbibl MAG21",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440030",
          location_id: "44",
          name_sv: "Humbibl MAG30",
          name_en: "Humbibl MAG30",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440031",
          location_id: "44",
          name_sv: "Humbibl MAG31",
          name_en: "Humbibl MAG31",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440032",
          location_id: "44",
          name_sv: "Humbibl MAG32",
          name_en: "Humbibl MAG32",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440033",
          location_id: "44",
          name_sv: "Humbibl MAG33",
          name_en: "Humbibl MAG33",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440035",
          location_id: "44",
          name_sv: "Humbibl MAG35",
          name_en: "Humbibl MAG35",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440036",
          location_id: "44",
          name_sv: "Humbibl MAG36",
          name_en: "Humbibl MAG36",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440040",
          location_id: "44",
          name_sv: "Humbibl MAG40",
          name_en: "Humbibl MAG40",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440042",
          location_id: "44",
          name_sv: "Humbibl MAG42",
          name_en: "Humbibl MAG42",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440046",
          location_id: "44",
          name_sv: "Humbibl MAG46",
          name_en: "Humbibl MAG46",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440047",
          location_id: "44",
          name_sv: "Humbibl MAG47",
          name_en: "Humbibl MAG47",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440050",
          location_id: "44",
          name_sv: "Humbibl MAG50",
          name_en: "Humbibl MAG50",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440051",
          location_id: "44",
          name_sv: "Humbibl MAG51",
          name_en: "Humbibl MAG51",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440052",
          location_id: "44",
          name_sv: "Humbibl MAG52",
          name_en: "Humbibl MAG52",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440054",
          location_id: "44",
          name_sv: "Humbibl MAG54",
          name_en: "Humbibl MAG54",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440056",
          location_id: "44",
          name_sv: "Humbibl MAG56",
          name_en: "Humbibl MAG56",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440057",
          location_id: "44",
          name_sv: "Humbibl MAG57",
          name_en: "Humbibl MAG57",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440058",
          location_id: "44",
          name_sv: "Humbibl MAG58",
          name_en: "Humbibl MAG58",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "446250",
          location_id: "44",
          name_sv: "Humbibl MAG5B Musik",
          name_en: "Humbibl MAG5B Musik",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440065",
          location_id: "44",
          name_sv: "Humbibl MAG65",
          name_en: "Humbibl MAG65",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440067",
          location_id: "44",
          name_sv: "Humbibl MAG67",
          name_en: "Humbibl MAG67",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440080",
          location_id: "44",
          name_sv: "Humbibl MAG80",
          name_en: "Humbibl MAG80",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440081",
          location_id: "44",
          name_sv: "Humbibl MAG81",
          name_en: "Humbibl MAG81",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440082",
          location_id: "44",
          name_sv: "Humbibl MAG82",
          name_en: "Humbibl MAG82",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440083",
          location_id: "44",
          name_sv: "Humbibl MAG83",
          name_en: "Humbibl MAG83",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440090",
          location_id: "44",
          name_sv: "Humbibl MAG90",
          name_en: "Humbibl MAG90",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440091",
          location_id: "44",
          name_sv: "Humbibl MAG91",
          name_en: "Humbibl MAG91",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440093",
          location_id: "44",
          name_sv: "Humbibl MAG93",
          name_en: "Humbibl MAG93",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440094",
          location_id: "44",
          name_sv: "Humbibl MAG94",
          name_en: "Humbibl MAG94",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440095",
          location_id: "44",
          name_sv: "Humbibl MAG95",
          name_en: "Humbibl MAG95",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440096",
          location_id: "44",
          name_sv: "Humbibl MAG96",
          name_en: "Humbibl MAG96",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440098",
          location_id: "44",
          name_sv: "Humbibl MIKROFICHE",
          name_en: "Humbibl MIKROFICHE",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "446299",
          location_id: "44",
          name_sv: "Humbibl Noterna är reserverade för HSM (deposition)",
          name_en: "Humbibl Noterna är reserverade för HSM (deposition)",
          is_open_loc: "",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "446260",
          location_id: "44",
          name_sv: "Plan 6A Musik och dramatik Ref",
          name_en: "Plan 6A Musik och dramatik Ref",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "446261",
          location_id: "44",
          name_sv: "Plan 6A Noter",
          name_en: "Plan 6A Noter",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "446262",
          location_id: "44",
          name_sv: "Plan 6A Pjäser",
          name_en: "Plan 6A Pjäser",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440062",
          location_id: "44",
          name_sv: "Entréhallen",
          name_en: "Entréhallen",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "1",
        },
        {
          id: "440073",
          location_id: "44",
          name_sv: "Entréplan, KvinnSam",
          name_en: "Entréplan, KvinnSam",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440074",
          location_id: "44",
          name_sv: "Entréplan, KvinnSam, Tidskrifter",
          name_en: "Entréplan, KvinnSam, Tidskrifter",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440061",
          location_id: "44",
          name_sv: "Plan 6A, Offentligt tryck",
          name_en: "Plan 6A, Offentligt tryck",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440045",
          location_id: "44",
          name_sv: "Humbibl RAR",
          name_en: "Humbibl RAR",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440075",
          location_id: "44",
          name_sv: "Entréplan, Referensböcker",
          name_en: "Entréplan, Referensböcker",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440070",
          location_id: "44",
          name_sv: "Entréplan, KvinnSam, Referensböcker",
          name_en: "Entréplan, KvinnSam, Referensböcker",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440064",
          location_id: "44",
          name_sv: "Plan 6A, Offentligt tryck",
          name_en: "Plan 6A, Offentligt tryck",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440078",
          location_id: "44",
          name_sv: "Entréplan, Bibliografier",
          name_en: "Entréplan, Bibliografier",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440005",
          location_id: "44",
          name_sv: "Humbiblioteket *MAG PER",
          name_en: "Humbiblioteket *MAG PER",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440015",
          location_id: "44",
          name_sv: "Humbiblioteket *MAG PER byte/gåva",
          name_en: "Humbiblioteket *MAG PER byte/gåva",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440009",
          location_id: "44",
          name_sv: "Humbiblioteket *MAG PER kategori 1",
          name_en: "Humbiblioteket *MAG PER kategori 1",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440019",
          location_id: "44",
          name_sv: "Humbiblioteket *MAG PER plikt 3",
          name_en: "Humbiblioteket *MAG PER plikt 3",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440025",
          location_id: "44",
          name_sv: "Humbiblioteket *MAG PER pliktlev",
          name_en: "Humbiblioteket *MAG PER pliktlev",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440007",
          location_id: "44",
          name_sv: "Humanistiska biblioteket",
          name_en: "Humanistiska biblioteket",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440017",
          location_id: "44",
          name_sv: "Humbiblioteket *MON byte/gåva",
          name_en: "Humbiblioteket *MON byte/gåva",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440027",
          location_id: "44",
          name_sv: "Humbiblioteket *MON pliktlev",
          name_en: "Humbiblioteket *MON pliktlev",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440004",
          location_id: "44",
          name_sv: "Plan 5, Tidskrifter",
          name_en: "Plan 5, Tidskrifter",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440014",
          location_id: "44",
          name_sv: "Plan 5, Tidskrifter",
          name_en: "Plan 5, Tidskrifter",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440024",
          location_id: "44",
          name_sv: "Plan 5, Tidskrifter",
          name_en: "Plan 5, Tidskrifter",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440079",
          location_id: "44",
          name_sv: "Entréplan, Referensböcker",
          name_en: "Entréplan, Referensböcker",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440013",
          location_id: "44",
          name_sv: "Humbiblioteket MAG PER byte/gåva",
          name_en: "Humbiblioteket MAG PER byte/gåva",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440006",
          location_id: "44",
          name_sv: "Humbiblioteket MAG PER kategori 1",
          name_en: "Humbiblioteket MAG PER kategori 1",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440029",
          location_id: "44",
          name_sv: "Humbiblioteket MAG PER plikt 3",
          name_en: "Humbiblioteket MAG PER plikt 3",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440023",
          location_id: "44",
          name_sv: "Humbiblioteket MAG PER pliktlev",
          name_en: "Humbiblioteket MAG PER pliktlev",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440008",
          location_id: "44",
          name_sv: "Humbiblioteket MON",
          name_en: "Humbiblioteket MON",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440018",
          location_id: "44",
          name_sv: "Humbiblioteket MON byte/gåva",
          name_en: "Humbiblioteket MON byte/gåva",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440028",
          location_id: "44",
          name_sv: "Humbiblioteket MON pliktlev",
          name_en: "Humbiblioteket MON pliktlev",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440026",
          location_id: "44",
          name_sv: "Plan 6A, Offentligt tryck",
          name_en: "Plan 6A, Offentligt tryck",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440002",
          location_id: "44",
          name_sv: "Plan 5, Tidskrifter",
          name_en: "Plan 5, Tidskrifter",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440012",
          location_id: "44",
          name_sv: "Plan 5, Tidskrifter",
          name_en: "Plan 5, Tidskrifter",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "440022",
          location_id: "44",
          name_sv: "Plan 5, Tidskrifter",
          name_en: "Plan 5, Tidskrifter",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
      ],
    },
    {
      id: "47",
      name_sv: "Pedagogiska biblioteket",
      name_en: "Education Library",
      pickup_location_id: "47",
      categories: ["PICKUP"],
      sublocations: [
        {
          id: "470088",
          location_id: "47",
          name_sv: "Gp Bestånd bib lvl f",
          name_en: "Gp Bestånd bib lvl f",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470089",
          location_id: "47",
          name_sv: "Gp Bestånd bib lvl g",
          name_en: "Gp Bestånd bib lvl g",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470099",
          location_id: "47",
          name_sv: "Fjärrlån",
          name_en: "Fjärrlån",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470008",
          location_id: "47",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470013",
          location_id: "47",
          name_sv: "Entréplan, Broschyrer",
          name_en: "Entréplan, Broschyrer",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470011",
          location_id: "47",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470100",
          location_id: "47",
          name_sv: "Pedag bibl Hänvisningspost",
          name_en: "Pedag bibl Hänvisningspost",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470300",
          location_id: "47",
          name_sv: "Pedag bibl Inköp",
          name_en: "Pedag bibl Inköp",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470017",
          location_id: "47",
          name_sv: "Kuggen Lindholmen ",
          name_en: "Kuggen Lindholmen ",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470003",
          location_id: "47",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "1",
        },
        {
          id: "470002",
          location_id: "47",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470016",
          location_id: "47",
          name_sv: "Nedre plan",
          name_en: "Nedre plan",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470015",
          location_id: "47",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470007",
          location_id: "47",
          name_sv: "Nedre plan",
          name_en: "Nedre plan",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470004",
          location_id: "47",
          name_sv: "Nedre plan",
          name_en: "Nedre plan",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470005",
          location_id: "47",
          name_sv: "Nedre plan",
          name_en: "Nedre plan",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470006",
          location_id: "47",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470012",
          location_id: "47",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470000",
          location_id: "47",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470001",
          location_id: "47",
          name_sv: "Pedagogiska biblioteket 01 (används ej)",
          name_en: "Pedagogiska biblioteket 01 (används ej)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "470009",
          location_id: "47",
          name_sv: "Pedagogiska biblioteket 09 (används ej)",
          name_en: "Pedagogiska biblioteket 09 (används ej)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
      ],
    },
    {
      id: "48",
      name_sv: "Ekonomiska biblioteket",
      name_en: "Economics Library",
      pickup_location_id: "48",
      categories: ["PICKUP"],
      sublocations: [
        {
          id: "480100",
          location_id: "48",
          name_sv: "Ekon bibl  Hänvisningspost",
          name_en: "Ekon bibl  Hänvisningspost",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480091",
          location_id: "48",
          name_sv: "Balkong 1",
          name_en: "Balkong 1",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480092",
          location_id: "48",
          name_sv: "Balkong 2",
          name_en: "Balkong 2",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480093",
          location_id: "48",
          name_sv: "Balkong 3",
          name_en: "Balkong 3",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480009",
          location_id: "48",
          name_sv: "Ekon bibl CD SAML",
          name_en: "Ekon bibl CD SAML",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480300",
          location_id: "48",
          name_sv: "Ekon bibl Inköp",
          name_en: "Ekon bibl Inköp",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480025",
          location_id: "48",
          name_sv: "Plan 5, Juridik",
          name_en: "Plan 5, Juridik",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480005",
          location_id: "48",
          name_sv: "Plan 3 (Entréplan)",
          name_en: "Plan 3 (Entréplan)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "1",
        },
        {
          id: "480012",
          location_id: "48",
          name_sv: "Plan 3 (Entréplan)",
          name_en: "Plan 3 (Entréplan)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480011",
          location_id: "48",
          name_sv: "Plan 3 (Entréplan), Läsesalen",
          name_en: "Plan 3 (Entréplan), Läsesalen",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480001",
          location_id: "48",
          name_sv: "Ekon bibl MAG",
          name_en: "Ekon bibl MAG",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480002",
          location_id: "48",
          name_sv: "Ekon bibl MAG PER",
          name_en: "Ekon bibl MAG PER",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480050",
          location_id: "48",
          name_sv: "Plan 4",
          name_en: "Plan 4",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480010",
          location_id: "48",
          name_sv: "Plan 1 (Källarplan)",
          name_en: "Plan 1 (Källarplan)",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480013",
          location_id: "48",
          name_sv: "Plan 1, Rum A",
          name_en: "Plan 1, Rum A",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480014",
          location_id: "48",
          name_sv: "Plan 1, Rum B",
          name_en: "Plan 1, Rum B",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480016",
          location_id: "48",
          name_sv: "Plan 1, Rum C",
          name_en: "Plan 1, Rum C",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480017",
          location_id: "48",
          name_sv: "Plan 1, Rum D",
          name_en: "Plan 1, Rum D",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480018",
          location_id: "48",
          name_sv: "Plan 1, Rum D, Nummerserien",
          name_en: "Plan 1, Rum D, Nummerserien",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480004",
          location_id: "48",
          name_sv: "Plan 3 (Entréplan), Referensböcker",
          name_en: "Plan 3 (Entréplan), Referensböcker",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480006",
          location_id: "48",
          name_sv: "Plan 4",
          name_en: "Plan 4",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480003",
          location_id: "48",
          name_sv: "Plan 4, Referensböcker",
          name_en: "Plan 4, Referensböcker",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480015",
          location_id: "48",
          name_sv: "Plan 5",
          name_en: "Plan 5",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480040",
          location_id: "48",
          name_sv: "Statistik",
          name_en: "Statistik",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480000",
          location_id: "48",
          name_sv: "Ekonomiska biblioteket",
          name_en: "Ekonomiska biblioteket",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480007",
          location_id: "48",
          name_sv: "Ekonomiska biblioteket 07 (används ej)",
          name_en: "Ekonomiska biblioteket 07 (används ej)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480008",
          location_id: "48",
          name_sv: "Ekonomiska biblioteket 08 (används ej)",
          name_en: "Ekonomiska biblioteket 08 (används ej)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480019",
          location_id: "48",
          name_sv: "Ekonomiska biblioteket 19 (används ej)",
          name_en: "Ekonomiska biblioteket 19 (används ej)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480030",
          location_id: "48",
          name_sv: "Ekonomiska biblioteket 30 (används ej)",
          name_en: "Ekonomiska biblioteket 30 (används ej)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480051",
          location_id: "48",
          name_sv: "Ekonomiska biblioteket 51 (används ej)",
          name_en: "Ekonomiska biblioteket 51 (används ej)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480055",
          location_id: "48",
          name_sv: "Ekonomiska biblioteket 55 (används ej)",
          name_en: "Ekonomiska biblioteket 55 (används ej)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480060",
          location_id: "48",
          name_sv: "Ekonomiska biblioteket 60 (används ej)",
          name_en: "Ekonomiska biblioteket 60 (används ej)",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "480099",
          location_id: "48",
          name_sv: "Fjärrlån",
          name_en: "Fjärrlån",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
      ],
    },
    {
      id: "60",
      name_sv: "Konstbiblioteket",
      name_en: "Art Library",
      pickup_location_id: "44",
      categories: ["PICKUP"],
      sublocations: [
        {
          id: "600005",
          location_id: "60",
          name_sv: "Konstbibl  MAG",
          name_en: "Konstbibl  MAG",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "600099",
          location_id: "60",
          name_sv: "Fjärrlån",
          name_en: "Fjärrlån",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "600100",
          location_id: "60",
          name_sv: "Konstbibl Hänvisningspost",
          name_en: "Konstbibl Hänvisningspost",
          is_open_loc: "",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "600300",
          location_id: "60",
          name_sv: "Konstbibl Inköp",
          name_en: "Konstbibl Inköp",
          is_open_loc: "",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "600002",
          location_id: "60",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "1",
        },
        {
          id: "600003",
          location_id: "60",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "600001",
          location_id: "60",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "600006",
          location_id: "60",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "600004",
          location_id: "60",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "600000",
          location_id: "60",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
      ],
    },
    {
      id: "66",
      name_sv: "Hälsovetarbackens bibliotek",
      name_en: "Hälsovetarbacken Library",
      pickup_location_id: "66",
      categories: [],
      sublocations: [
        {
          id: "660300",
          location_id: "66",
          name_sv: "Hälsovet Inköp",
          name_en: "Hälsovet Inköp",
          is_open_loc: "",
          is_paging_loc: "1",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "660000",
          location_id: "66",
          name_sv: "Hälsovetarbacken Återlämning",
          name_en: "Hälsovetarbacken Återlämning",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
        {
          id: "660001",
          location_id: "66",
          name_sv: "Entréplan",
          name_en: "Entréplan",
          is_open_loc: "1",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
      ],
    },
    {
      id: "70",
      name_sv: "Biomedicinska biblioteket, fjärrlån",
      name_en: "Biomedical Library, ILL",
      pickup_location_id: "70",
      categories: [],
      sublocations: [
        {
          id: "700099",
          location_id: "70",
          name_sv: "Fjärrlån",
          name_en: "Fjärrlån",
          is_open_loc: "",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
      ],
    },
    {
      id: "74",
      name_sv: "Humanistiska biblioteket, fjärrlån",
      name_en: "Humanities Library, ILL",
      pickup_location_id: "74",
      categories: [],
      sublocations: [
        {
          id: "740099",
          location_id: "74",
          name_sv: "Fjärrlån",
          name_en: "Fjärrlån",
          is_open_loc: "",
          is_paging_loc: "",
          is_open_pickup_loc: "",
          is_kursbok_loc: "",
        },
      ],
    },
  ];

  // Extend the original locations with localized names based on the locale query parameter
  const extendedLocations = originalLocations.map((location) => ({
    ...location,
    name: locale === "en" ? location.name_en : location.name_sv,
    sublocations: location.sublocations.map((sublocation) => ({
      ...sublocation,
      name: locale === "en" ? sublocation.name_en : sublocation.name_sv,
    })),
  }));

  try {
    return extendedLocations;
  } catch (error) {
    console.error("Error returning locations:", error);
  } finally {
    console.log("Seeding completed.");
  }
});
